// Code generated by github.com/daotl/cbor-gen. DO NOT EDIT.

package testing

import (
	"fmt"
	"io"
	"math"
	"sort"

	cbg "github.com/daotl/cbor-gen"
	cid "github.com/ipfs/go-cid"
	xerrors "golang.org/x/xerrors"
)

var _ = xerrors.Errorf
var _ = cid.Undef
var _ = math.E
var _ = sort.Sort

var lengthBufSignedArray = []byte{129}

func (t *SignedArray) MarshalCBOR(w io.Writer) (n int, err error) {
	if t == nil {
		return w.Write(cbg.CborNull)
	}
	if n_, err := w.Write(lengthBufSignedArray); err != nil {
		return n_, err
	} else {
		n += n_
	}

	scratch := make([]byte, 9)

	// t.Signed ([]uint64) (slice)
	if len(t.Signed) > cbg.MaxLength {
		return n, xerrors.Errorf("Slice value in field t.Signed was too long")
	}

	if n_, err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajArray, uint64(len(t.Signed))); err != nil {
		return n + n_, err
	} else {
		n += n_
	}
	for _, v := range t.Signed {
		if n_, err := cbg.CborWriteHeader(w, cbg.MajUnsignedInt, uint64(v)); err != nil {
			return n + n_, err
		} else {
			n += n_
		}
	}
	return n, nil
}

func (t *SignedArray) UnmarshalCBOR(r io.Reader) (int, error) {
	bytesRead := 0
	*t = SignedArray{}

	br := cbg.GetPeeker(r)
	scratch := make([]byte, 8)

	maj, extra, read, err := cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return bytesRead, err
	}
	bytesRead += read
	if maj != cbg.MajArray {
		return bytesRead, fmt.Errorf("cbor input should be of type array")
	}

	if extra != 1 {
		return bytesRead, fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.Signed ([]uint64) (slice)

	maj, extra, read, err = cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return bytesRead, err
	}
	bytesRead += read

	if extra > cbg.MaxLength {
		return bytesRead, fmt.Errorf("t.Signed: array too large (%d)", extra)
	}

	if maj != cbg.MajArray {
		return bytesRead, fmt.Errorf("expected cbor array")
	}

	if extra > 0 {
		t.Signed = make([]uint64, extra)
	}

	for i := 0; i < int(extra); i++ {

		maj, val, read, err := cbg.CborReadHeaderBuf(br, scratch)
		if err != nil {
			return bytesRead, xerrors.Errorf("failed to read uint64 for t.Signed slice: %w", err)
		}
		bytesRead += read

		if maj != cbg.MajUnsignedInt {
			return bytesRead, xerrors.Errorf("value read for array t.Signed was not a uint, instead got %d", maj)
		}

		t.Signed[i] = uint64(val)
	}

	return bytesRead, nil
}

var lengthBufSimpleTypeOne = []byte{139}

func (t *SimpleTypeOne) MarshalCBOR(w io.Writer) (n int, err error) {
	if t == nil {
		return w.Write(cbg.CborNull)
	}
	if n_, err := w.Write(lengthBufSimpleTypeOne); err != nil {
		return n_, err
	} else {
		n += n_
	}

	scratch := make([]byte, 9)

	// t.Foo (string) (string)
	if len(t.Foo) > cbg.MaxLength {
		return n, xerrors.Errorf("Value in field t.Foo was too long")
	}

	if n_, err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajTextString, uint64(len(t.Foo))); err != nil {
		return n + n_, err
	} else {
		n += n_
	}
	if n_, err := io.WriteString(w, string(t.Foo)); err != nil {
		return n + n_, err
	} else {
		n += n_
	}

	// t.Value (uint64) (uint64)

	if n_, err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajUnsignedInt, uint64(t.Value)); err != nil {
		return n + n_, err
	} else {
		n += n_
	}

	// t.Binary ([]uint8) (slice)
	if len(t.Binary) > cbg.ByteArrayMaxLen {
		return n, xerrors.Errorf("Byte array in field t.Binary was too long")
	}

	if n_, err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajByteString, uint64(len(t.Binary))); err != nil {
		return n + n_, err
	} else {
		n += n_
	}

	if n_, err := w.Write(t.Binary[:]); err != nil {
		return n + n_, err
	} else {
		n += n_
	}

	// t.Signed (int64) (int64)
	if t.Signed >= 0 {
		if n_, err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajUnsignedInt, uint64(t.Signed)); err != nil {
			return n + n_, err
		} else {
			n += n_
		}
	} else {
		if n_, err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajNegativeInt, uint64(-t.Signed-1)); err != nil {
			return n + n_, err
		} else {
			n += n_
		}
	}

	// t.NString (testing.NamedString) (string)
	if len(t.NString) > cbg.MaxLength {
		return n, xerrors.Errorf("Value in field t.NString was too long")
	}

	if n_, err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajTextString, uint64(len(t.NString))); err != nil {
		return n + n_, err
	} else {
		n += n_
	}
	if n_, err := io.WriteString(w, string(t.NString)); err != nil {
		return n + n_, err
	} else {
		n += n_
	}

	// t.U8 (uint8) (uint8)
	if n_, err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajUnsignedInt, uint64(t.U8)); err != nil {
		return n + n_, err
	} else {
		n += n_
	}

	// t.U16 (uint16) (uint16)
	if n_, err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajUnsignedInt, uint64(t.U16)); err != nil {
		return n + n_, err
	} else {
		n += n_
	}

	// t.U32 (uint32) (uint32)
	if n_, err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajUnsignedInt, uint64(t.U32)); err != nil {
		return n + n_, err
	} else {
		n += n_
	}

	// t.I8 (int8) (int8)
	if t.I8 >= 0 {
		if n_, err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajUnsignedInt, uint64(t.I8)); err != nil {
			return n + n_, err
		} else {
			n += n_
		}
	} else {
		if n_, err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajNegativeInt, uint64(-t.I8-1)); err != nil {
			return n + n_, err
		} else {
			n += n_
		}
	}

	// t.I16 (int16) (int16)
	if t.I16 >= 0 {
		if n_, err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajUnsignedInt, uint64(t.I16)); err != nil {
			return n + n_, err
		} else {
			n += n_
		}
	} else {
		if n_, err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajNegativeInt, uint64(-t.I16-1)); err != nil {
			return n + n_, err
		} else {
			n += n_
		}
	}

	// t.I32 (int32) (int32)
	if t.I32 >= 0 {
		if n_, err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajUnsignedInt, uint64(t.I32)); err != nil {
			return n + n_, err
		} else {
			n += n_
		}
	} else {
		if n_, err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajNegativeInt, uint64(-t.I32-1)); err != nil {
			return n + n_, err
		} else {
			n += n_
		}
	}
	return n, nil
}

func (t *SimpleTypeOne) UnmarshalCBOR(r io.Reader) (int, error) {
	bytesRead := 0
	*t = SimpleTypeOne{}

	br := cbg.GetPeeker(r)
	scratch := make([]byte, 8)

	maj, extra, read, err := cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return bytesRead, err
	}
	bytesRead += read
	if maj != cbg.MajArray {
		return bytesRead, fmt.Errorf("cbor input should be of type array")
	}

	if extra != 11 {
		return bytesRead, fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.Foo (string) (string)

	{
		sval, read, err := cbg.ReadStringBuf(br, scratch)
		if err != nil {
			return bytesRead, err
		}
		bytesRead += read

		t.Foo = string(sval)
	}
	// t.Value (uint64) (uint64)

	{

		maj, extra, read, err = cbg.CborReadHeaderBuf(br, scratch)
		if err != nil {
			return bytesRead, err
		}
		bytesRead += read
		if maj != cbg.MajUnsignedInt {
			return bytesRead, fmt.Errorf("wrong type for uint64 field")
		}
		t.Value = uint64(extra)

	}
	// t.Binary ([]uint8) (slice)

	maj, extra, read, err = cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return bytesRead, err
	}
	bytesRead += read

	if extra > cbg.ByteArrayMaxLen {
		return bytesRead, fmt.Errorf("t.Binary: byte array too large (%d)", extra)
	}
	if maj != cbg.MajByteString {
		return bytesRead, fmt.Errorf("expected byte array")
	}

	if extra > 0 {
		t.Binary = make([]uint8, extra)
	}

	if read, err := io.ReadFull(br, t.Binary[:]); err != nil {
		return bytesRead, err
	} else {
		bytesRead += read
	}
	// t.Signed (int64) (int64)
	{
		maj, extra, read, err := cbg.CborReadHeaderBuf(br, scratch)
		var extraI int64
		if err != nil {
			return bytesRead, err
		}
		bytesRead += read
		switch maj {
		case cbg.MajUnsignedInt:
			extraI = int64(extra)
			if extraI < 0 {
				return bytesRead, fmt.Errorf("int64 positive overflow")
			}
		case cbg.MajNegativeInt:
			extraI = int64(extra)
			if extraI < 0 {
				return bytesRead, fmt.Errorf("int64 negative oveflow")
			}
			extraI = -1 - extraI
		default:
			return bytesRead, fmt.Errorf("wrong type for int64 field: %d", maj)
		}

		t.Signed = int64(extraI)
	}
	// t.NString (testing.NamedString) (string)

	{
		sval, read, err := cbg.ReadStringBuf(br, scratch)
		if err != nil {
			return bytesRead, err
		}
		bytesRead += read

		t.NString = NamedString(sval)
	}
	// t.U8 (uint8) (uint8)

	maj, extra, read, err = cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return bytesRead, err
	}
	bytesRead += read
	if maj != cbg.MajUnsignedInt {
		return bytesRead, fmt.Errorf("wrong type for uint64 field")
	}
	if extra > math.MaxUint64 {
		return bytesRead, fmt.Errorf("integer in input was too large for uint64 field")
	}
	t.U8 = uint8(extra)
	// t.U16 (uint16) (uint16)

	maj, extra, read, err = cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return bytesRead, err
	}
	bytesRead += read
	if maj != cbg.MajUnsignedInt {
		return bytesRead, fmt.Errorf("wrong type for uint64 field")
	}
	if extra > math.MaxUint64 {
		return bytesRead, fmt.Errorf("integer in input was too large for uint64 field")
	}
	t.U16 = uint16(extra)
	// t.U32 (uint32) (uint32)

	maj, extra, read, err = cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return bytesRead, err
	}
	bytesRead += read
	if maj != cbg.MajUnsignedInt {
		return bytesRead, fmt.Errorf("wrong type for uint64 field")
	}
	if extra > math.MaxUint64 {
		return bytesRead, fmt.Errorf("integer in input was too large for uint64 field")
	}
	t.U32 = uint32(extra)
	// t.I8 (int8) (int8)
	{
		maj, extra, read, err := cbg.CborReadHeaderBuf(br, scratch)
		var extraI int64
		if err != nil {
			return bytesRead, err
		}
		bytesRead += read
		switch maj {
		case cbg.MajUnsignedInt:
			extraI = int64(extra)
			if extraI < 0 {
				return bytesRead, fmt.Errorf("int64 positive overflow")
			}
		case cbg.MajNegativeInt:
			extraI = int64(extra)
			if extraI < 0 {
				return bytesRead, fmt.Errorf("int64 negative oveflow")
			}
			extraI = -1 - extraI
		default:
			return bytesRead, fmt.Errorf("wrong type for int64 field: %d", maj)
		}

		t.I8 = int8(extraI)
	}
	// t.I16 (int16) (int16)
	{
		maj, extra, read, err := cbg.CborReadHeaderBuf(br, scratch)
		var extraI int64
		if err != nil {
			return bytesRead, err
		}
		bytesRead += read
		switch maj {
		case cbg.MajUnsignedInt:
			extraI = int64(extra)
			if extraI < 0 {
				return bytesRead, fmt.Errorf("int64 positive overflow")
			}
		case cbg.MajNegativeInt:
			extraI = int64(extra)
			if extraI < 0 {
				return bytesRead, fmt.Errorf("int64 negative oveflow")
			}
			extraI = -1 - extraI
		default:
			return bytesRead, fmt.Errorf("wrong type for int64 field: %d", maj)
		}

		t.I16 = int16(extraI)
	}
	// t.I32 (int32) (int32)
	{
		maj, extra, read, err := cbg.CborReadHeaderBuf(br, scratch)
		var extraI int64
		if err != nil {
			return bytesRead, err
		}
		bytesRead += read
		switch maj {
		case cbg.MajUnsignedInt:
			extraI = int64(extra)
			if extraI < 0 {
				return bytesRead, fmt.Errorf("int64 positive overflow")
			}
		case cbg.MajNegativeInt:
			extraI = int64(extra)
			if extraI < 0 {
				return bytesRead, fmt.Errorf("int64 negative oveflow")
			}
			extraI = -1 - extraI
		default:
			return bytesRead, fmt.Errorf("wrong type for int64 field: %d", maj)
		}

		t.I32 = int32(extraI)
	}
	return bytesRead, nil
}

var lengthBufSimpleTypeTwo = []byte{137}

func (t *SimpleTypeTwo) MarshalCBOR(w io.Writer) (n int, err error) {
	if t == nil {
		return w.Write(cbg.CborNull)
	}
	if n_, err := w.Write(lengthBufSimpleTypeTwo); err != nil {
		return n_, err
	} else {
		n += n_
	}

	scratch := make([]byte, 9)

	// t.Stuff (testing.SimpleTypeTwo) (struct)
	if n_, err := t.Stuff.MarshalCBOR(w); err != nil {
		return n + n_, err
	} else {
		n += n_
	}

	// t.Others ([]uint64) (slice)
	if len(t.Others) > cbg.MaxLength {
		return n, xerrors.Errorf("Slice value in field t.Others was too long")
	}

	if n_, err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajArray, uint64(len(t.Others))); err != nil {
		return n + n_, err
	} else {
		n += n_
	}
	for _, v := range t.Others {
		if n_, err := cbg.CborWriteHeader(w, cbg.MajUnsignedInt, uint64(v)); err != nil {
			return n + n_, err
		} else {
			n += n_
		}
	}

	// t.SignedOthers ([]int64) (slice)
	if len(t.SignedOthers) > cbg.MaxLength {
		return n, xerrors.Errorf("Slice value in field t.SignedOthers was too long")
	}

	if n_, err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajArray, uint64(len(t.SignedOthers))); err != nil {
		return n + n_, err
	} else {
		n += n_
	}
	for _, v := range t.SignedOthers {
		if v >= 0 {
			if n_, err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajUnsignedInt, uint64(v)); err != nil {
				return n + n_, err
			} else {
				n += n_
			}
		} else {
			if n_, err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajNegativeInt, uint64(-v-1)); err != nil {
				return n + n_, err
			} else {
				n += n_
			}
		}
	}

	// t.Test ([][]uint8) (slice)
	if len(t.Test) > cbg.MaxLength {
		return n, xerrors.Errorf("Slice value in field t.Test was too long")
	}

	if n_, err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajArray, uint64(len(t.Test))); err != nil {
		return n + n_, err
	} else {
		n += n_
	}
	for _, v := range t.Test {
		if len(v) > cbg.ByteArrayMaxLen {
			return n, xerrors.Errorf("Byte array in field v was too long")
		}

		if n_, err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajByteString, uint64(len(v))); err != nil {
			return n + n_, err
		} else {
			n += n_
		}

		if n_, err := w.Write(v[:]); err != nil {
			return n + n_, err
		} else {
			n += n_
		}
	}

	// t.Dog (string) (string)
	if len(t.Dog) > cbg.MaxLength {
		return n, xerrors.Errorf("Value in field t.Dog was too long")
	}

	if n_, err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajTextString, uint64(len(t.Dog))); err != nil {
		return n + n_, err
	} else {
		n += n_
	}
	if n_, err := io.WriteString(w, string(t.Dog)); err != nil {
		return n + n_, err
	} else {
		n += n_
	}

	// t.Numbers ([]testing.NamedNumber) (slice)
	if len(t.Numbers) > cbg.MaxLength {
		return n, xerrors.Errorf("Slice value in field t.Numbers was too long")
	}

	if n_, err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajArray, uint64(len(t.Numbers))); err != nil {
		return n + n_, err
	} else {
		n += n_
	}
	for _, v := range t.Numbers {
		if n_, err := cbg.CborWriteHeader(w, cbg.MajUnsignedInt, uint64(v)); err != nil {
			return n + n_, err
		} else {
			n += n_
		}
	}

	// t.Pizza (uint64) (uint64)

	if t.Pizza == nil {
		if n_, err := w.Write(cbg.CborNull); err != nil {
			return n + n_, err
		} else {
			n += n_
		}
	} else {
		if n_, err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajUnsignedInt, uint64(*t.Pizza)); err != nil {
			return n + n_, err
		} else {
			n += n_
		}
	}

	// t.PointyPizza (testing.NamedNumber) (uint64)

	if t.PointyPizza == nil {
		if n_, err := w.Write(cbg.CborNull); err != nil {
			return n + n_, err
		} else {
			n += n_
		}
	} else {
		if n_, err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajUnsignedInt, uint64(*t.PointyPizza)); err != nil {
			return n + n_, err
		} else {
			n += n_
		}
	}

	// t.Arrrrrghay ([3]testing.SimpleTypeOne) (array)
	if len(t.Arrrrrghay) > cbg.MaxLength {
		return n, xerrors.Errorf("Slice value in field t.Arrrrrghay was too long")
	}

	if n_, err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajArray, uint64(len(t.Arrrrrghay))); err != nil {
		return n + n_, err
	} else {
		n += n_
	}
	for _, v := range t.Arrrrrghay {
		if n_, err := v.MarshalCBOR(w); err != nil {
			return n + n_, err
		} else {
			n += n_
		}
	}
	return n, nil
}

func (t *SimpleTypeTwo) UnmarshalCBOR(r io.Reader) (int, error) {
	bytesRead := 0
	*t = SimpleTypeTwo{}

	br := cbg.GetPeeker(r)
	scratch := make([]byte, 8)

	maj, extra, read, err := cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return bytesRead, err
	}
	bytesRead += read
	if maj != cbg.MajArray {
		return bytesRead, fmt.Errorf("cbor input should be of type array")
	}

	if extra != 9 {
		return bytesRead, fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.Stuff (testing.SimpleTypeTwo) (struct)

	{

		b, err := br.ReadByte()
		if err != nil {
			return bytesRead, err
		}
		bytesRead++
		if b != cbg.CborNull[0] {
			if err := br.UnreadByte(); err != nil {
				return bytesRead, err
			}
			bytesRead--
			t.Stuff = new(SimpleTypeTwo)
			if read, err := t.Stuff.UnmarshalCBOR(br); err != nil {
				return bytesRead, xerrors.Errorf("unmarshaling t.Stuff pointer: %w", err)
			} else {
				bytesRead += read
			}
		}

	}
	// t.Others ([]uint64) (slice)

	maj, extra, read, err = cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return bytesRead, err
	}
	bytesRead += read

	if extra > cbg.MaxLength {
		return bytesRead, fmt.Errorf("t.Others: array too large (%d)", extra)
	}

	if maj != cbg.MajArray {
		return bytesRead, fmt.Errorf("expected cbor array")
	}

	if extra > 0 {
		t.Others = make([]uint64, extra)
	}

	for i := 0; i < int(extra); i++ {

		maj, val, read, err := cbg.CborReadHeaderBuf(br, scratch)
		if err != nil {
			return bytesRead, xerrors.Errorf("failed to read uint64 for t.Others slice: %w", err)
		}
		bytesRead += read

		if maj != cbg.MajUnsignedInt {
			return bytesRead, xerrors.Errorf("value read for array t.Others was not a uint, instead got %d", maj)
		}

		t.Others[i] = uint64(val)
	}

	// t.SignedOthers ([]int64) (slice)

	maj, extra, read, err = cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return bytesRead, err
	}
	bytesRead += read

	if extra > cbg.MaxLength {
		return bytesRead, fmt.Errorf("t.SignedOthers: array too large (%d)", extra)
	}

	if maj != cbg.MajArray {
		return bytesRead, fmt.Errorf("expected cbor array")
	}

	if extra > 0 {
		t.SignedOthers = make([]int64, extra)
	}

	for i := 0; i < int(extra); i++ {
		{
			maj, extra, read, err := cbg.CborReadHeaderBuf(br, scratch)
			var extraI int64
			if err != nil {
				return bytesRead, err
			}
			bytesRead += read
			switch maj {
			case cbg.MajUnsignedInt:
				extraI = int64(extra)
				if extraI < 0 {
					return bytesRead, fmt.Errorf("int64 positive overflow")
				}
			case cbg.MajNegativeInt:
				extraI = int64(extra)
				if extraI < 0 {
					return bytesRead, fmt.Errorf("int64 negative oveflow")
				}
				extraI = -1 - extraI
			default:
				return bytesRead, fmt.Errorf("wrong type for int64 field: %d", maj)
			}

			t.SignedOthers[i] = int64(extraI)
		}
	}

	// t.Test ([][]uint8) (slice)

	maj, extra, read, err = cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return bytesRead, err
	}
	bytesRead += read

	if extra > cbg.MaxLength {
		return bytesRead, fmt.Errorf("t.Test: array too large (%d)", extra)
	}

	if maj != cbg.MajArray {
		return bytesRead, fmt.Errorf("expected cbor array")
	}

	if extra > 0 {
		t.Test = make([][]uint8, extra)
	}

	for i := 0; i < int(extra); i++ {
		{
			var maj byte
			var extra uint64
			var err error

			maj, extra, read, err = cbg.CborReadHeaderBuf(br, scratch)
			if err != nil {
				return bytesRead, err
			}
			bytesRead += read

			if extra > cbg.ByteArrayMaxLen {
				return bytesRead, fmt.Errorf("t.Test[i]: byte array too large (%d)", extra)
			}
			if maj != cbg.MajByteString {
				return bytesRead, fmt.Errorf("expected byte array")
			}

			if extra > 0 {
				t.Test[i] = make([]uint8, extra)
			}

			if read, err := io.ReadFull(br, t.Test[i][:]); err != nil {
				return bytesRead, err
			} else {
				bytesRead += read
			}
		}
	}

	// t.Dog (string) (string)

	{
		sval, read, err := cbg.ReadStringBuf(br, scratch)
		if err != nil {
			return bytesRead, err
		}
		bytesRead += read

		t.Dog = string(sval)
	}
	// t.Numbers ([]testing.NamedNumber) (slice)

	maj, extra, read, err = cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return bytesRead, err
	}
	bytesRead += read

	if extra > cbg.MaxLength {
		return bytesRead, fmt.Errorf("t.Numbers: array too large (%d)", extra)
	}

	if maj != cbg.MajArray {
		return bytesRead, fmt.Errorf("expected cbor array")
	}

	if extra > 0 {
		t.Numbers = make([]NamedNumber, extra)
	}

	for i := 0; i < int(extra); i++ {

		maj, val, read, err := cbg.CborReadHeaderBuf(br, scratch)
		if err != nil {
			return bytesRead, xerrors.Errorf("failed to read uint64 for t.Numbers slice: %w", err)
		}
		bytesRead += read

		if maj != cbg.MajUnsignedInt {
			return bytesRead, xerrors.Errorf("value read for array t.Numbers was not a uint, instead got %d", maj)
		}

		t.Numbers[i] = NamedNumber(val)
	}

	// t.Pizza (uint64) (uint64)

	{

		b, err := br.ReadByte()
		if err != nil {
			return bytesRead, err
		}
		bytesRead++
		if b != cbg.CborNull[0] {
			if err := br.UnreadByte(); err != nil {
				return bytesRead, err
			}
			bytesRead--
			maj, extra, read, err = cbg.CborReadHeaderBuf(br, scratch)
			if err != nil {
				return bytesRead, err
			}
			bytesRead += read
			if maj != cbg.MajUnsignedInt {
				return bytesRead, fmt.Errorf("wrong type for uint64 field")
			}
			typed := uint64(extra)
			t.Pizza = &typed
		}

	}
	// t.PointyPizza (testing.NamedNumber) (uint64)

	{

		b, err := br.ReadByte()
		if err != nil {
			return bytesRead, err
		}
		bytesRead++
		if b != cbg.CborNull[0] {
			if err := br.UnreadByte(); err != nil {
				return bytesRead, err
			}
			bytesRead--
			maj, extra, read, err = cbg.CborReadHeaderBuf(br, scratch)
			if err != nil {
				return bytesRead, err
			}
			bytesRead += read
			if maj != cbg.MajUnsignedInt {
				return bytesRead, fmt.Errorf("wrong type for uint64 field")
			}
			typed := NamedNumber(extra)
			t.PointyPizza = &typed
		}

	}
	// t.Arrrrrghay ([3]testing.SimpleTypeOne) (array)

	maj, extra, read, err = cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return bytesRead, err
	}
	bytesRead += read

	if extra > cbg.MaxLength {
		return bytesRead, fmt.Errorf("t.Arrrrrghay: array too large (%d)", extra)
	}

	if maj != cbg.MajArray {
		return bytesRead, fmt.Errorf("expected cbor array")
	}

	if extra != 3 {
		return bytesRead, fmt.Errorf("expected array to have 3 elements")
	}

	t.Arrrrrghay = [3]SimpleTypeOne{}

	for i := 0; i < int(extra); i++ {

		var v SimpleTypeOne
		if read, err := v.UnmarshalCBOR(br); err != nil {
			return bytesRead, err
		} else {
			bytesRead += read
		}

		t.Arrrrrghay[i] = v
	}

	return bytesRead, nil
}

var lengthBufDeferredContainer = []byte{131}

func (t *DeferredContainer) MarshalCBOR(w io.Writer) (n int, err error) {
	if t == nil {
		return w.Write(cbg.CborNull)
	}
	if n_, err := w.Write(lengthBufDeferredContainer); err != nil {
		return n_, err
	} else {
		n += n_
	}

	scratch := make([]byte, 9)

	// t.Stuff (testing.SimpleTypeOne) (struct)
	if n_, err := t.Stuff.MarshalCBOR(w); err != nil {
		return n + n_, err
	} else {
		n += n_
	}

	// t.Deferred (typegen.Deferred) (struct)
	if n_, err := t.Deferred.MarshalCBOR(w); err != nil {
		return n + n_, err
	} else {
		n += n_
	}

	// t.Value (uint64) (uint64)

	if n_, err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajUnsignedInt, uint64(t.Value)); err != nil {
		return n + n_, err
	} else {
		n += n_
	}

	return n, nil
}

func (t *DeferredContainer) UnmarshalCBOR(r io.Reader) (int, error) {
	bytesRead := 0
	*t = DeferredContainer{}

	br := cbg.GetPeeker(r)
	scratch := make([]byte, 8)

	maj, extra, read, err := cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return bytesRead, err
	}
	bytesRead += read
	if maj != cbg.MajArray {
		return bytesRead, fmt.Errorf("cbor input should be of type array")
	}

	if extra != 3 {
		return bytesRead, fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.Stuff (testing.SimpleTypeOne) (struct)

	{

		b, err := br.ReadByte()
		if err != nil {
			return bytesRead, err
		}
		bytesRead++
		if b != cbg.CborNull[0] {
			if err := br.UnreadByte(); err != nil {
				return bytesRead, err
			}
			bytesRead--
			t.Stuff = new(SimpleTypeOne)
			if read, err := t.Stuff.UnmarshalCBOR(br); err != nil {
				return bytesRead, xerrors.Errorf("unmarshaling t.Stuff pointer: %w", err)
			} else {
				bytesRead += read
			}
		}

	}
	// t.Deferred (typegen.Deferred) (struct)

	{

		t.Deferred = new(cbg.Deferred)

		if read, err := t.Deferred.UnmarshalCBOR(br); err != nil {
			return bytesRead, xerrors.Errorf("failed to read deferred field: %w", err)
		} else {
			bytesRead += read
		}
	}
	// t.Value (uint64) (uint64)

	{

		maj, extra, read, err = cbg.CborReadHeaderBuf(br, scratch)
		if err != nil {
			return bytesRead, err
		}
		bytesRead += read
		if maj != cbg.MajUnsignedInt {
			return bytesRead, fmt.Errorf("wrong type for uint64 field")
		}
		t.Value = uint64(extra)

	}
	return bytesRead, nil
}

var lengthBufFixedArrays = []byte{131}

func (t *FixedArrays) MarshalCBOR(w io.Writer) (n int, err error) {
	if t == nil {
		return w.Write(cbg.CborNull)
	}
	if n_, err := w.Write(lengthBufFixedArrays); err != nil {
		return n_, err
	} else {
		n += n_
	}

	scratch := make([]byte, 9)

	// t.Bytes ([20]uint8) (array)
	if len(t.Bytes) > cbg.ByteArrayMaxLen {
		return n, xerrors.Errorf("Byte array in field t.Bytes was too long")
	}

	if n_, err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajByteString, uint64(len(t.Bytes))); err != nil {
		return n + n_, err
	} else {
		n += n_
	}

	if n_, err := w.Write(t.Bytes[:]); err != nil {
		return n + n_, err
	} else {
		n += n_
	}

	// t.Uint8 ([20]uint8) (array)
	if len(t.Uint8) > cbg.ByteArrayMaxLen {
		return n, xerrors.Errorf("Byte array in field t.Uint8 was too long")
	}

	if n_, err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajByteString, uint64(len(t.Uint8))); err != nil {
		return n + n_, err
	} else {
		n += n_
	}

	if n_, err := w.Write(t.Uint8[:]); err != nil {
		return n + n_, err
	} else {
		n += n_
	}

	// t.Uint64 ([20]uint64) (array)
	if len(t.Uint64) > cbg.MaxLength {
		return n, xerrors.Errorf("Slice value in field t.Uint64 was too long")
	}

	if n_, err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajArray, uint64(len(t.Uint64))); err != nil {
		return n + n_, err
	} else {
		n += n_
	}
	for _, v := range t.Uint64 {
		if n_, err := cbg.CborWriteHeader(w, cbg.MajUnsignedInt, uint64(v)); err != nil {
			return n + n_, err
		} else {
			n += n_
		}
	}
	return n, nil
}

func (t *FixedArrays) UnmarshalCBOR(r io.Reader) (int, error) {
	bytesRead := 0
	*t = FixedArrays{}

	br := cbg.GetPeeker(r)
	scratch := make([]byte, 8)

	maj, extra, read, err := cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return bytesRead, err
	}
	bytesRead += read
	if maj != cbg.MajArray {
		return bytesRead, fmt.Errorf("cbor input should be of type array")
	}

	if extra != 3 {
		return bytesRead, fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.Bytes ([20]uint8) (array)

	maj, extra, read, err = cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return bytesRead, err
	}
	bytesRead += read

	if extra > cbg.ByteArrayMaxLen {
		return bytesRead, fmt.Errorf("t.Bytes: byte array too large (%d)", extra)
	}
	if maj != cbg.MajByteString {
		return bytesRead, fmt.Errorf("expected byte array")
	}

	if extra != 20 {
		return bytesRead, fmt.Errorf("expected array to have 20 elements")
	}

	t.Bytes = [20]uint8{}

	if read, err := io.ReadFull(br, t.Bytes[:]); err != nil {
		return bytesRead, err
	} else {
		bytesRead += read
	}
	// t.Uint8 ([20]uint8) (array)

	maj, extra, read, err = cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return bytesRead, err
	}
	bytesRead += read

	if extra > cbg.ByteArrayMaxLen {
		return bytesRead, fmt.Errorf("t.Uint8: byte array too large (%d)", extra)
	}
	if maj != cbg.MajByteString {
		return bytesRead, fmt.Errorf("expected byte array")
	}

	if extra != 20 {
		return bytesRead, fmt.Errorf("expected array to have 20 elements")
	}

	t.Uint8 = [20]uint8{}

	if read, err := io.ReadFull(br, t.Uint8[:]); err != nil {
		return bytesRead, err
	} else {
		bytesRead += read
	}
	// t.Uint64 ([20]uint64) (array)

	maj, extra, read, err = cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return bytesRead, err
	}
	bytesRead += read

	if extra > cbg.MaxLength {
		return bytesRead, fmt.Errorf("t.Uint64: array too large (%d)", extra)
	}

	if maj != cbg.MajArray {
		return bytesRead, fmt.Errorf("expected cbor array")
	}

	if extra != 20 {
		return bytesRead, fmt.Errorf("expected array to have 20 elements")
	}

	t.Uint64 = [20]uint64{}

	for i := 0; i < int(extra); i++ {

		maj, val, read, err := cbg.CborReadHeaderBuf(br, scratch)
		if err != nil {
			return bytesRead, xerrors.Errorf("failed to read uint64 for t.Uint64 slice: %w", err)
		}
		bytesRead += read

		if maj != cbg.MajUnsignedInt {
			return bytesRead, xerrors.Errorf("value read for array t.Uint64 was not a uint, instead got %d", maj)
		}

		t.Uint64[i] = uint64(val)
	}

	return bytesRead, nil
}

var lengthBufThingWithSomeTime = []byte{131}

func (t *ThingWithSomeTime) MarshalCBOR(w io.Writer) (n int, err error) {
	if t == nil {
		return w.Write(cbg.CborNull)
	}
	if n_, err := w.Write(lengthBufThingWithSomeTime); err != nil {
		return n_, err
	} else {
		n += n_
	}

	scratch := make([]byte, 9)

	// t.When (typegen.CborTime) (struct)
	if n_, err := t.When.MarshalCBOR(w); err != nil {
		return n + n_, err
	} else {
		n += n_
	}

	// t.Stuff (int64) (int64)
	if t.Stuff >= 0 {
		if n_, err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajUnsignedInt, uint64(t.Stuff)); err != nil {
			return n + n_, err
		} else {
			n += n_
		}
	} else {
		if n_, err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajNegativeInt, uint64(-t.Stuff-1)); err != nil {
			return n + n_, err
		} else {
			n += n_
		}
	}

	// t.CatName (string) (string)
	if len(t.CatName) > cbg.MaxLength {
		return n, xerrors.Errorf("Value in field t.CatName was too long")
	}

	if n_, err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajTextString, uint64(len(t.CatName))); err != nil {
		return n + n_, err
	} else {
		n += n_
	}
	if n_, err := io.WriteString(w, string(t.CatName)); err != nil {
		return n + n_, err
	} else {
		n += n_
	}
	return n, nil
}

func (t *ThingWithSomeTime) UnmarshalCBOR(r io.Reader) (int, error) {
	bytesRead := 0
	*t = ThingWithSomeTime{}

	br := cbg.GetPeeker(r)
	scratch := make([]byte, 8)

	maj, extra, read, err := cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return bytesRead, err
	}
	bytesRead += read
	if maj != cbg.MajArray {
		return bytesRead, fmt.Errorf("cbor input should be of type array")
	}

	if extra != 3 {
		return bytesRead, fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.When (typegen.CborTime) (struct)

	{

		if read, err := t.When.UnmarshalCBOR(br); err != nil {
			return bytesRead, xerrors.Errorf("unmarshaling t.When: %w", err)
		} else {
			bytesRead += read
		}

	}
	// t.Stuff (int64) (int64)
	{
		maj, extra, read, err := cbg.CborReadHeaderBuf(br, scratch)
		var extraI int64
		if err != nil {
			return bytesRead, err
		}
		bytesRead += read
		switch maj {
		case cbg.MajUnsignedInt:
			extraI = int64(extra)
			if extraI < 0 {
				return bytesRead, fmt.Errorf("int64 positive overflow")
			}
		case cbg.MajNegativeInt:
			extraI = int64(extra)
			if extraI < 0 {
				return bytesRead, fmt.Errorf("int64 negative oveflow")
			}
			extraI = -1 - extraI
		default:
			return bytesRead, fmt.Errorf("wrong type for int64 field: %d", maj)
		}

		t.Stuff = int64(extraI)
	}
	// t.CatName (string) (string)

	{
		sval, read, err := cbg.ReadStringBuf(br, scratch)
		if err != nil {
			return bytesRead, err
		}
		bytesRead += read

		t.CatName = string(sval)
	}
	return bytesRead, nil
}
